---
- name: Command | Wait for coredns started
  ansible.builtin.command:
    cmd: "kubectl -n kube-system get svc kube-dns -o jsonpath='{.spec.clusterIP}'"
  changed_when: false
  check_mode: false
  register: __dns_svc_ip
  until: __dns_svc_ip.rc == 0
  retries: 10
  delay: 30

- name: Set_fact | coredns ip address
  ansible.builtin.set_fact:
    _coredns_ip: "{{ __dns_svc_ip.stdout }}"

- name: Template | nodelocaldns manifest
  ansible.builtin.template:
    src: nodelocaldns-daemonset.j2
    dest: /etc/kubernetes/nodelocaldns-daemonset.yaml
    mode: '0644'
  register: __nodelocaldns_manifest

- name: Command | Apply nodelocaldns manifest
  ansible.builtin.command:
    cmd: kubectl apply -f /etc/kubernetes/nodelocaldns-daemonset.yaml
  when: __nodelocaldns_manifest.changed
