---
# TODO: Make k8s reconfig when kubeadm config changed
- name: Template | kubeadm-config.yaml
  ansible.builtin.template:
    src: kubeadm-config.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: "0644"

- name: Stat | k8s ca presense
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: __kubeadm_ca

- name: Block | Kubeadm init
  when: not __kubeadm_ca.stat.exists
  block:
    - name: Command | Init control node
      ansible.builtin.command:
        cmd: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
      register: __kubeadm_init
      timeout: 600
  rescue:
    - name: Command | Reset Node because of init failure
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - kubeadm reset -f
        - iptables -F
        - iptables -t nat -F
        - iptables -t mangle -F
        - iptables -X
        - nft flush ruleset
        - ipset destroy
        - ipvsadm -C

- name: File | Link for kubeconfig
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    state: link

- name: Command | kubectl cluster-info
  ansible.builtin.command:
    cmd: "kubectl cluster-info"
  changed_when: false
  register: __cluster_info
  until: __cluster_info.rc == 0
  timeout: 30
  retries: 10
  delay: 30
