---
- name: Stat | kubelet.conf
  ansible.builtin.stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: __kubelet_conf

- name: Command | kubeadm join worker
  when: not __kubelet_conf.stat.exists
  ansible.builtin.command:
    cmd: >-
      kubeadm join {{ hostvars[groups['k8s_master'][0]]._join_path }}
      --token {{ hostvars[groups['k8s_master'][0]]._join_token }}
      --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_master'][0]]._join_ca_hash }}
