---
- name: Include | Prepare to worker join
  ansible.builtin.include_tasks: prepare.yaml
  when: inventory_hostname == ansible_play_hosts_all[0]

- name: Include | Join worker node
  ansible.builtin.include_tasks: join.yaml
  when: inventory_hostname in groups['k8s_worker']
